workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      vars:
        PROJECT_DIR: "aladia"
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          cd $PROJECT_DIR
          flutter pub get
      - name: Run unit tests
        script: |
          cd $PROJECT_DIR
          flutter test
      - name: Build APK
        script: |
          cd $PROJECT_DIR
          flutter build apk --release
      - name: Archive build artifacts
        script: |
          cd $PROJECT_DIR
          mkdir -p artifacts/
          mv build/app/outputs/flutter-apk/app-release.apk artifacts/
artifacts:
  - artifacts/app-release.apk
